language: generic

sudo: required
env:
  - REPO=405528688887.dkr.ecr.eu-west-1.amazonaws.com/example

script: make

deploy:
  provider: script
  script: scripts/build-and-push-image.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|develop$
