apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
data:
  # base64-encoded via 'echo -n xxxxxxxxxxxxxxxxxxxx | base64'
  username: YWRtaW4=
  password: dmVyeV9sb25nX3Bhc3N3ZA==
